site_name: RBM
site_description: River Basin Model - Stream Temperature
site_author: J Yearsley
repo_url: https://github.com/jyearsley/RBM_Mk/tree/develop
theme: readthedocs
docs_dir: docs
site_dir: site
use_directory_urls: true

