site_name: RBM_Mk
site_description: River Basin Model - Stream Temperature
site_author: J Yearsley
repo_url: https://github.com/jyearsley/RBM_Mk/tree/master
theme: readthedocs
site_url: https://jyearsleyrbm-mk.readthedocs.org
docs_dir: docs
site_dir: site
use_directory_urls: true

pages:
# Main pages
- Home: 'index.md'
- About:
    - 'Model Overview': 'Overview/ModelOverview.md'
    - 'References': 'Documentation/References.md'
    - 'FAQ': 'FAQ/FAQ.md'
    - 'Contact': 'contact.md'
    - 'Links': 'links.md'
- Documentation:
    - 'Tutorial':   'Documentation/tutorial.md'
    - 'How to run RBM (Salmon River example)': 'Documentation/run_RBM.md'
- Development:
    - 'Development': 'Development/ModelDevelopment.md'
    - 'Release Notes': 'Development/ReleaseNotes.md'
- Downloads:
    - Datasets: 'Datasets/Datasets.md'
    - Code: 'SourceCode/Code.md'

markdown_extensions:
    - toc:
        permalink: True
    - admonition:
    - fenced_code:
