site_name: RBM
site_description: River Basin Model - Stream Temperature
site_author: J Yearsley
repo_url: https://github.com/jyearsley/RBM_Mk/tree/develop
#site_url: jyearsleyrbm-mk.rtfd.io
theme: readthedocs
docs_dir: docs
site_dir: site
use_directory_urls: true

pages:
# Main pages
- Home: 'index.md'
- About:
    - 'Model Overview': 'Overview/ModelOverview.md'
    - 'References': 'Documentation/References.md'
    - 'FAQ': 'FAQ/FAQ.md'
    - 'Contact': 'contact.md'
    - 'Links': 'links.md'